enable_relay = true
http_bind_addr = "[::]:3340"
enable_quic_addr_discovery = false
enable_metrics = true
metrics_bind_addr = "[::]:9090"

[limits]
accept_conn_limit = 20.0
accept_conn_burst = 50

[limits.client.rx]
bytes_per_second = 10485760
max_burst_bytes = 20971520

